let ErrorType = {
    
    GENERAL_ERROR : {id: 1, httpCode: 600, message : "A big fuck up which we'll never tell you of had just happend. And now : A big fat lie....'A general error ....'", isShowStackTrace: true},
    USER_NAME_ALREADY_EXIST : {id: 2, httpCode: 601, message : "User name already exist or client have already account", isShowStackTrace: false},
    USER_NAME_NOT_INSERT:{id:3,httpCode:400,message:"you forgot enter your userName",isShowStackTrace:false},
    PASSWORD_NOT_INSERT:{id:4,httpCode:400,message:"you forgot enter your password",isShowStackTrace:false},
    FIRST_NAME_NOT_INSERT:{id:5,httpCode:400,message:"you forgot enter your firstName",isShowStackTrace:false},
    LAST_NAME_NOT_INSERT:{id:6,httpCode:400,message:"you forgot enter your lastName",isShowStackTrace:false},
    TYPE_NOT_INSERT:{id:7,httpCode:400,message:"you forgot enter your type",isShowStackTrace:false},
    USER_NAME_NOT_EMAIL:{id:8,httpCode:400,message:"userName must be your email",isShowStackTrace:false},
    PASSWORD_TOO_SHORT:{id:9,httpCode:400,message:"your password is too short",isShowStackTrace:false},
    PASSWORD_TOO_LONG:{id:10,httpCode:400,message:"your password is too long",isShowStackTrace:false},
    IDENTITY_NOT_INSERT:{id:11,httpCode:400,message:"you forgot insert your  identity",isShowStackTrace:false},
    CITY_NOT_INSERT:{id:12,httpCode:400,message:"you forgot insert your city",isShowStackTrace:false},
    STREET_NOT_INSERT:{id:13,httpCode:400,message:"you forgot insert your street",isShowStackTrace:false},
    YOU_NOT_INSERT_IDENTITY:{id:14,httpCode:400,message:"you not insert identity",isShowStackTrace:false},
    PRODUCT_NAME_NOT_INSER:{id:15,httpCode:400,message:"you not insert product name",isShowStackTrace:false},
    CATEGORY_ID_NOT_INSERT:{id:16,httpCode:400,message:"you not category id",isShowStackTrace:false},
    PRICE_NOT_INSERT:{id:17,httpCode:400,message:"you not insert product price",isShowStackTrace:false},
    IMAGE_URL_NOT_INSERT:{id:18,httpCode:400,message:"you not insert image url",isShowStackTrace:false},
    SHIPPING_DATE_OVER:{id:19,httpCode:400,message:"you insert shipping date that was over",isShowStackTrace:false},
    NOT_PROVIDE_IMAGE_FILE:{id:19,httpCode:400,message:"image of product not get successfully",isShowStackTrace:false},
    NOT_GIVING_PRODUCT_ID:{id:20,httpCode:400,message:"not giving cart product id",isShowStackTrace:false},
    NOT_GIVING_PRODUCT_CAPACITY:{id:20,httpCode:400,message:"not giving product capacity",isShowStackTrace:false},
    NOT_GIVING_PRODUCT_PRICE:{id:20,httpCode:400,message:"not giving product price",isShowStackTrace:false},
    NOT_GIVING_PRODUCTS_PRICE:{id:20,httpCode:400,message:"not giving products price",isShowStackTrace:false},
    NOT_GIVING_SHIPPING_DATE:{id:20,httpCode:400,message:"not giving shipping date",isShowStackTrace:false},
    NOT_GIVING_CARTID:{id:20,httpCode:400,message:"not giving cart id",isShowStackTrace:false},
    SORREY_WE_HAVE_THREE_ORDER:{id:20,httpCode:400,message:"sorrey there is a 3 order for this day please take another date",isShowStackTrace:false},
    LOGIN_FAILD : {id: 19, httpCode: 401, message : "Login failed, invalid user name or password", isShowStackTrace: false},
    USER_NAME_NOT_EMAIL_1 : {id: 20, httpCode: 401, message : "your userName must be of kind email", isShowStackTrace: false},
    USER_NAME_NOT_EXIT : {id: 21, httpCode: 401, message : "user not exit", isShowStackTrace: false},
    BED_PASSWORD : {id: 22, httpCode: 401, message : "password is not correct", isShowStackTrace: false},
}

module.exports = ErrorType;